config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'

  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users, only: [:show, :index] do
    resources :tweets, except: [:index]
    resources :follows, only: [:index, :create, :destroy]
    get :followers, to: 'follows#followers'
  end
  get '/search' => 'tweets#search_partial'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user, :class_name => "User"
  belongs_to :target_user, :class_name => "User"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  MIN_LIST_COUNT = 1
  MAX_LIST_COUNT = 100

  DEFAULT_LIST_COUNT = 10

  scope :with_search_options, -> (options) {
    relation = offset(options[:offset]).limit(options[:limit])
    relation = relation.where(user_id: options[:user_id]) if options[:user_id].present?
    if options[:follow_user_id].present?
      relation = relation.where("(tweets.user_id=?) OR (tweets.user_id IN (SELECT target_user_id FROM follows WHERE user_id=?))", options[:follow_user_id], options[:follow_user_id])
    end
    relation = relation.where('tweets.created_at <= ?', Time.at(options[:time])) if options[:time].present?
    relation.order(created_at: :desc, id: :desc)
  }

  def self.search(options)
    options[:offset] = 0 if options[:offset].blank?
    options[:limit] = [[options[:limit] || DEFAULT_LIST_COUNT, MIN_LIST_COUNT].max, MAX_LIST_COUNT].min

    with_search_options(options).includes(:user).joins(:user)
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :tweets, autosave: true, :dependent => :destroy
  has_many :follows, autosave: true, :dependent => :destroy
  has_many :followers, autosave: true, :class_name => "Follow", :foreign_key => "target_user_id", :dependent => :destroy

  def is_follow?(user_id)
    self.follows.find_by(target_user_id: user_id).present?
  end
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :set_user, only: [:index, :followers, :create, :destroy]

  def index
    @follows = @user.follows
  end

  def followers
    @followers = @user.followers
  end

  def create
    target_user_id = params[:id]
    unless @user.is_follow?(target_user_id)
      @user.follows << Follow.new(target_user_id: target_user_id)
      @user.save!
    end
    redirect_to user_path(target_user_id)
  rescue
    redirect_to user_path(target_user_id), notice: "フォローに失敗しました"
  end

  def destroy
    target_user_id = params[:id]
    follow = @user.follows.find_by(target_user_id: target_user_id)
    
    follow.destroy if follow.present?
    redirect_to user_path(target_user_id)
  rescue
    redirect_to user_path(target_user_id), notice: "フォロー解除に失敗しました"
  end

private

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_user, only: [:show, :new, :create, :edit, :update, :destroy, :tweet_list_partial]
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  def tweet_list_partial
    render partial: 'tweet_list_partial', locals: { user: @user }
  end

  # GET /search
  def search_partial
    options = {
      time: Time.now.to_i,
      limit: Tweet::DEFAULT_LIST_COUNT,
      offset: 0
    }

    options[:time] = params[:time].to_i if params[:time].present?
    options[:user_id] = params[:user_id].to_i if params[:user_id].present?
    options[:follow_user_id] = params[:follow_user_id].to_i if params[:follow_user_id].present?
    options[:offset] = params[:offset].to_i if params[:offset].present?

    render partial: 'search_partial', locals: { tweets: Tweet.search(options), options: options }
  end

  def show
  end

  def new
    @tweet = Tweet.new
  end

  def edit
  end

  def create
    raise unless verify_user?
    
    @tweet = Tweet.new(tweet_params)
    @tweet.user = @user
    from_path = params[:tweet][:from_path] if params[:tweet][:from_path]

    if @tweet.save
      if from_path.present?
        redirect_to from_path, notice: 'Tweet was successfully created.'
      else
        redirect_to user_tweet_path(@user, @tweet), notice: 'Tweet was successfully created.'
      end
    else
      render :new
    end
  end

  def update
    raise unless verify_user?
    
    from_path = params[:tweet][:from_path] if params[:tweet][:from_path]
    if @tweet.update(tweet_params)
      if from_path.present?
        redirect_to from_path, notice: 'Tweet was successfully updated.'
      else
        redirect_to user_tweet_path(@user, @tweet), notice: 'Tweet was successfully updated.'
      end
    else
      render :edit
    end
  end

  def destroy
    raise unless verify_user?

    from_path = params[:tweet][:from_path] if params[:tweet][:from_path]
    @tweet.destroy
    if from_path.present?
      redirect_to from_path, notice: 'Tweet was successfully destroyed.'
    else
      redirect_to user_path(@user), notice: 'Tweet was successfully destroyed.'
    end
  end

private

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def tweet_params
    params.require(:tweet).permit(:user_id, :content)
  end

  def verify_user?
    current_user.id == @user&.id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.where.not(id: current_user.id)
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Like-Twitter(sample)"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

  def bootstrap_class_for(flash_type)
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-danger"
      when :alert
        "alert-warning"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/follows/followers.html.erb
<% provide(:title, "Follower Users") %>

<ul class="users">
  <% @followers.each do |follower| %>
    <%= render partial: 'users/list_partial', locals: { user: follower.user } %>
  <% end %>
</ul>

app/views/follows/index.html.erb
<% provide(:title, "Follow Users") %>

<ul class="users">
  <% @follows.each do |follow| %>
    <%= render partial: 'users/list_partial', locals: { user: follow.target_user } %>
  <% end %>
</ul>

app/views/home/index.html.erb
<% provide(:title, "Home") %>

<%
  @tweet = Tweet.new
  @tweet.user = current_user
%>
<%= render 'tweets/form', tweet: @tweet %>

<hr/>

<%= render partial: 'tweets/tweet_list_partial', locals: { follow_user: current_user } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Like-Twitter", root_path, id: "logo" %>
        <% if current_user.present? %>
          <nav>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "Users", users_path %></li>
              <li><%= link_to "Profile", user_path(current_user) %></li>
              <li><%= link_to "Sign out", users_sign_out_path %></li>
            </ul>
          </nav>
        <% end %>
      </div>
    </header>

    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert <%= bootstrap_class_for(key) %>"><%= value %></div>
      <% end %>

      <div class="row">
        <aside class="col-md-3">
          <section>
            <% if current_user.present? %>
              <h1>
                <%= link_to current_user.email, edit_user_registration_path %>
              </h1>
              <table class="table table-condensed text-center">
                <tr class="info">
                  <th>Tweets</th>
                  <th><%= link_to "Follows", user_follows_path(current_user) %></th>
                  <th><%= link_to "Followers", user_followers_path(current_user) %></th>
                </tr>
                <tr>
                  <td><%= current_user.tweets.count.to_s(:delimited) %></td>
                  <td><%= current_user.follows.count.to_s(:delimited) %></td>
                  <td><%= current_user.followers.count.to_s(:delimited) %></td>
                </tr>
              </table>
            <% end %>
          </section>
        </aside>
        <div class="main-content col-md-6">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: [current_user, tweet], local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :content, id: :tweet_content, class: "form-control", placeholder: "いまどうしてる？" %>
    <%= form.hidden_field :from_path, id: :tweet_from_path, value: request.fullpath %>
  </div>
  <div class="field text-right">
    <%= form.submit "Tweet!" %>
  </div>
<% end %>

app/views/tweets/_loading.html.erb
<li id="loading-line" class="alert alert-info text-center" data-user="<%= options[:user_id] %>" data-follow-user="<%= options[:follow_user_id] %>" data-time="<%= options[:time] %>" data-offset="<%= options[:offset] %>">
  <span class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></span>
  Loading...
</li>

app/views/tweets/_search_partial.html.erb
<% tweets.each do |tweet| %>
  <li class="tweet">
    <div>
      <%= link_to tweet.user.email, user_path(tweet.user), class: "tweet-user" %>
      :
      posted at <%= Time.zone.local_to_utc(tweet.updated_at).in_time_zone.strftime('%Y-%m-%d %H:%M:%S') %>
    </div>
    <div class="tweet-content">
      <%= tweet.content %>
    </div>
    <% if current_user.id == tweet.user_id %>
      <div class="tweet-action text-right">
        <%= link_to 'Edit', edit_user_tweet_path(current_user, tweet) %>
        |
        <%= link_to 'Destroy', user_tweet_path(current_user, tweet), method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>
  </li>
<% end %>

<% if tweets.size > 0 and tweets.size == options[:limit] %>
  <%= render partial: 'tweets/loading', locals: { options: options.merge(offset: options[:offset] + tweets.count) } %>
<% end %>

app/views/tweets/_tweet_list_partial.html.erb
<%
  options = {
    offset: 0,
  }
  options[:user_id] = user.id if defined?(user) and user.present?
  options[:follow_user_id] = follow_user.id if defined?(follow_user) and follow_user.present?
%>

<ul class="tweets">
  <%= render partial: 'tweets/loading', locals: { options: options } %>
</ul>

<%= javascript_tag do %>
  $(function() {
    $('.tweets').on('inview', '#loading-line', function(event, isInView) {
      if (isInView) {
        var loading = $(this)
        setTimeout(
          function() {
            var params = {
              user_id: loading.data('user'),
              follow_user_id: loading.data('follow-user'),
              time: loading.data('time'),
              offset: loading.data('offset')
            }

            $.get("<%= search_path %>",
              params,
              function(data){
                var parent = loading.parent();
                loading.remove();
                parent.append(data)
              }
            );
          },0
        );
      }
    });
  });
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', user_tweet_path(current_user, @tweet) %> |
<%= link_to 'Back', user_path(current_user) %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', users_path(current_user) %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @tweet.user_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @tweet.content %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

app/views/users/_list_partial.html.erb
<li>
  <%= link_to user.email, user_path(user) %>
  (
  Tweets:<%= user.tweets.count.to_s(:delimited) %>,
  Follows:<%= user.follows.count.to_s(:delimited) %>,
  Followers:<%= user.followers.count.to_s(:delimited) %>
  )
</li>

app/views/users/index.html.erb
<% provide(:title, "User List") %>

<ul class="users">
  <% @users.each do |user| %>
    <%= render partial: 'users/list_partial', locals: { user: user } %>
  <% end %>
</ul>

app/views/users/show.html.erb
<% provide(:title, @user.email) %>

<h2><%= @user.email %></h2>

<% if current_user.id == @user.id %>
  <%
    @tweet = Tweet.new
    @tweet.user = @user
  %>
  <%= render 'tweets/form', tweet: @tweet %>
<% else %>
  <div id="follow-action" class="text-center">
    <% if current_user.is_follow?(@user.id) %>
      <%= link_to "Unfollow", user_follow_path(current_user, @user.id), method: :delete, class: "btn btn-danger", data: { confirm: "フォロー解除してもよろしいですか？"} %>
    <% else %>
      <%= link_to "Follow", user_follows_path(current_user, params: {id: @user.id}), method: :post, class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

<hr/>

<%= render partial: 'tweets/tweet_list_partial', locals: { user: @user } %>